[package]
name = "latte-soft/lucide-icons"
description = "Library to Use the Lucide Icon Set (https://lucide.dev) in Roblox"
version = "0.1.3"
license = "MIT AND ISC"
authors = ["Latte Softworks <contact@latte.to>"]

exclude = ["**"]
include = ["LICENSE.md", "wally.toml", "default.project.json", "version-info.luau", "lib", "lib**"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
